{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Mining\n",
    "\n",
    "## CRISP-DM\n",
    "\n",
    "The CRoss Industry Standard Process for Data Mining (CRISP-DM) is a process model with six phases that describes the data science life cycle.\n",
    "\n",
    "![CRISP-DM](https://www.datascience-pm.com/wp-content/uploads/2021/02/CRISP-DM.png)\n",
    "\n",
    "| **Phase**               | **Tasks**                                      |\n",
    "|------------------------|-----------------------------------------------|\n",
    "| **Business Understanding** | Business objectives, Assessment, Data mining goals, Project plan |\n",
    "| **Data Understanding**     | Collect, Describe, Visualize, Verify quality |\n",
    "| **Data Preparation**       | Select, Clean, Integrate, Format, Standardize/Discretize/Transform, Create new fields |\n",
    "| **Modeling**               | Select techniques, Test design, Build model, Assess model |\n",
    "| **Evaluation**             | Evaluate results, Review process, Decide next step |\n",
    "| **Data Mining**            | Learn from data, Find common patterns, Predict future results |\n",
    "\n",
    "Common problems: Data quality may be poor, data may be missing or noisy and patterns found may not be exact, not useful or simply not interesting\n",
    "\n",
    "### Common data mining tasks\n",
    "- Predictive\n",
    "  - **Classification** Predict the class\n",
    "  - **Regression** Predict a number\n",
    "  - **Time Series Analysis** Predict next value in the series\n",
    "- Descriptive\n",
    "  - **Clustering** Grouping by similarities\n",
    "  - **Summarization** Summarize and generalize data\n",
    "  - **Association Rules** Discover connection between items\n",
    "  - **Sequence Discovery** Find patterns in sequential data\n",
    "\n",
    "## Data Cleaning\n",
    "1. Import data\n",
    "2. Merge datasets\n",
    "3. Handle missing data\n",
    "4. Standardization\n",
    "5. Normalization\n",
    "6. Remove duplicates\n",
    "\n",
    "## Data Transformation\n",
    "- **Transforming** Applying a function to an attribute\n",
    "- **Summarizing** Grouping\n",
    "- **Discretization**\n",
    "  - Transform numeric values into categorical ones\n",
    "  - Binarizing\n",
    "  - Binning\n",
    "- **Handle missing values**\n",
    "  - Remove records\n",
    "  - Imputation\n",
    "    - Replace by a value\n",
    "    - Use median/mean\n",
    "    - Predict using kNN\n",
    "- **Standardization** Substitute values by the *Z score*\n",
    "- **Normalization** Rescale values to the **[0; 1]** interval"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
